version: "3"

services:
  api:
    build: ./api
    command: npm start
    volumes:
      - ./api:/usr/node-api
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1455:1433
    environment:
      SA_PASSWORD: "dev@1234"
      ACCEPT_EULA: "Y"

    volumes:
      - ./data:/var/opt/mssql/data

  website:
    image: php:apache
    ports:
      - 5001:80
    volumes:
      - ./website:/var/www/html
    depends_on:
      - api
